## Qs 1 - Implement a perceptron to simulate a 2-input NAND gate.

### Creating the perceptron class. 

In [5]:
import numpy as np

class Perceptron:
    def __init__(self, input_size):
        
        self.weights = np.zeros(input_size + 1)  # Initializing weights to zero including the bias
    
    def predict(self, x):

        result = np.dot(x, self.weights)
        return 1 if result > 0 else 0  

    def train(self, X, y, max_iterations=50):
       
        X_processed = np.copy(X)
        for i in range(len(y)):        # Negating all zero-class examples
            if y[i] == 0:     
                X_processed[i] = -X_processed[i]
                y[i] = 1 
        
        iteration = 0
        while iteration < max_iterations:
            all_correct = True
            for i in range(len(X_processed)):
                xi = X_processed[i]
                target = y[i]
                predicted = self.predict(xi)
                
            
                if predicted != target:
                    print(f"Iteration {iteration+1}: Updating weights")
                    print(f"  Before update: weights = {self.weights}")
                    self.weights = self.weights + xi
                    print(f"  After update: weights = {self.weights}")
                    all_correct = False
            
            if all_correct:
                print(f"Converged after {iteration+1} iterations")
                break
            
            iteration += 1
        
        if iteration == max_iterations:
            print("Maximum iterations reached without convergence")

    def test(self, X):
        results = []
        for xi in X:
            results.append(self.predict(xi))
        return results



### Creating and testing the NAND gate. 

In [6]:
# NAND gate input and output

X = np.array([[0, 0, -1],  # Input1, Input2, Bias ; The input includes the bias term (x0=-1)
              [0, 1, -1],
              [1, 0, -1],
              [1, 1, -1]])

y = np.array([1, 1, 1, 0])  # Output of the NAND gate


perceptron = Perceptron(input_size=2)  # 2 inputs + 1 bias
perceptron.train(X, y)


print("\nTesting the trained perceptron:") 
predicted_outputs = perceptron.test(X)
print(f"Inputs: \n{X}")
print(f"Predicted outputs: {predicted_outputs}")
print(f"Final weights: {perceptron.weights}")



Testing the trained perceptron:
Inputs: 
[[ 0  0 -1]
 [ 0  1 -1]
 [ 1  0 -1]
 [ 1  1 -1]]
Predicted outputs: [1, 1, 1, 0]
Final weights: [-3. -2. -4.]


### Creating and testing the XOR gate. 

In [4]:
# XOR gate input and output

X = np.array([[0, 0, -1],  # Input1, Input2, Bias
              [0, 1, -1],
              [1, 0, -1],
              [1, 1, -1]])

y = np.array([0, 1, 1, 0])  # Output of the XOR gate


perceptron = Perceptron(input_size=2)  # 2 inputs + 1 bias
perceptron.train(X, y)


print("\nTesting the trained perceptron:") 
predicted_outputs = perceptron.test(X)
print(f"Inputs: \n{X}")
print(f"Predicted outputs: {predicted_outputs}")
print(f"Final weights: {perceptron.weights}")


Iteration 1: Updating weights
  Before update: weights = [0. 0. 0.]
  After update: weights = [0. 0. 1.]
Iteration 1: Updating weights
  Before update: weights = [0. 0. 1.]
  After update: weights = [0. 1. 0.]
Iteration 1: Updating weights
  Before update: weights = [0. 1. 0.]
  After update: weights = [ 1.  1. -1.]
Iteration 1: Updating weights
  Before update: weights = [ 1.  1. -1.]
  After update: weights = [0. 0. 0.]
Iteration 2: Updating weights
  Before update: weights = [0. 0. 0.]
  After update: weights = [0. 0. 1.]
Iteration 2: Updating weights
  Before update: weights = [0. 0. 1.]
  After update: weights = [0. 1. 0.]
Iteration 2: Updating weights
  Before update: weights = [0. 1. 0.]
  After update: weights = [ 1.  1. -1.]
Iteration 2: Updating weights
  Before update: weights = [ 1.  1. -1.]
  After update: weights = [0. 0. 0.]
Iteration 3: Updating weights
  Before update: weights = [0. 0. 0.]
  After update: weights = [0. 0. 1.]
Iteration 3: Updating weights
  Before upda

### Conclusion:

In this notebook, we implemented and trained a perceptron to classify the XOR logic gate using two inputs and a bias term. Despite the simplicity of the perceptron model, we observed that it was unable to solve the XOR problem effectively due to its linear nature. This behavior was evident as the weights failed to converge to a solution that could correctly classify all input-output pairs of the XOR gate.

The iterative weight updates demonstrated that a single-layer perceptron struggles with non-linearly separable data, such as XOR. This highlights the necessity of using more advanced models, such as multi-layer perceptrons (MLPs) or neural networks with non-linear activation functions, to solve such problems.