## Tutorial 

In [1]:
import torch 

In [2]:
torch.__version__

'2.0.0+cu117'

In [3]:
# Create a tensor
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)
print(x.size()) 

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
torch.Size([3, 3])


In [5]:
torch.cuda.is_available()

# Create a tensor on the GPU
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], device='cuda')
print(x)


tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')


In [6]:
# Perform addition on the GPU
y = torch.tensor([[9, 8, 7], [6, 5, 4], [3, 2, 1]], device='cuda')
z = x + y
print(z)

tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]], device='cuda:0')


In [7]:
# Move the tensor back to the CPU
z = z.to('cpu')
print(z)


tensor([[10, 10, 10],
        [10, 10, 10],
        [10, 10, 10]])


In [9]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]], device='cuda')
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')


In [16]:
x.reshape(1, -1).shape
print(x)

# create a numpy array and convert it to a tensor
import numpy as np
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = torch.tensor(x)
print(x)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], device='cuda:0')
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)


: 